[[pages]]
path = "src/pages/Welcome.py"
name = "ğŸ  Toolbox"
icon = "ğŸ "

[[pages]]
path = "src/pages/Instructions.py"
name = "ğŸ“ Instructions"
icon = "ğŸ“"

[[pages]]
path = "src/pages/Data_Upload.py"
name = "â¬†ï¸ Upload data"
icon = "â¬†ï¸"

[[pages]]
path = "src/pages/Statistical_Analysis.py"
name = "ğŸ“Š Statistical analysis"
icon = "ğŸ“Š"

[[pages]]
path = "src/pages/Ecological_Diversity.py"
name = "ğŸ“– Ecological measures"
icon = "ğŸ“–"

[[pages]]
path = "src/pages/Machine_Learning.py"
name = "ğŸŒ AI predictions"
icon = "ğŸŒ"
